
name: android_build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: cache gradle
      id: cache-gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-
    
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.0
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build

  # Upload to Artifacts
  # Deleted because of lack of discspace on GitHub Actions
  # - name: Upload apk file
  #   uses: actions/upload-artifact@v1
  #   with:
  #     name: apk
  #     path: app/build/outputs/apk/debug/app-debug.apk
